#!/bin/sh
#
# Changes the partition UUIDs to new random values.
#

set -e

case "${1}" in
  prereqs)
    exit 0
    ;;
esac

# shellcheck disable=SC1091
. /scripts/functions

if ! grep -q ' resize' /proc/cmdline; then
  exit 0
fi

get_variables () {
  if ! BOOT_PART_DEV=$(findmnt -n -o SOURCE -s -F "${rootmnt?}/etc/fstab" /boot/firmware); then
    exit 0
  fi

  ROOT_DEV_NAME="$(lsblk -no pkname "$ROOT")"
  ROOT_DEV="/dev/$ROOT_DEV_NAME"

  ROOT_PART_NAME="$(lsblk -no kname "$ROOT")"
  ROOT_PART_NUM=$(cat "/sys/block/$ROOT_DEV_NAME/$ROOT_PART_NAME/partition")
}

fix_diskid () {
  if parted -s -m -l "$ROOT_DEV" | grep -q ':gpt:'; then
    # Change partition UUIDs
    OLD_BOOT_PARTUUID=$(sgdisk -i 1 "$ROOT_DEV" | grep "Partition unique GUID" | awk '{ print tolower($NF) }')
    OLD_ROOT_PARTUUID=$(sgdisk -i 2 "$ROOT_DEV" | grep "Partition unique GUID" | awk '{ print tolower($NF) }')

    NEW_BOOT_UUID=$(cat /proc/sys/kernel/random/uuid)
    NEW_ROOT_UUID=$(cat /proc/sys/kernel/random/uuid)
    NEW_DISK_UUID=$(cat /proc/sys/kernel/random/uuid)
    sgdisk --partition-guid=1:$NEW_BOOT_UUID --partition-guid=2:$NEW_ROOT_UUID --disk-guid=$NEW_DISK_UUID "$ROOT_DEV"

    if [ $? -eq 0 ]; then
      partprobe
      sed -i "s/${OLD_BOOT_PARTUUID}/${NEW_BOOT_UUID}/g" ${rootmnt?}/etc/fstab
      sed -i "s/${OLD_ROOT_PARTUUID}/${NEW_ROOT_UUID}/g" ${rootmnt?}/etc/fstab
      sed -i "s/${OLD_ROOT_PARTUUID}/${NEW_ROOT_UUID}/g" /run/new_diskid/cmdline.txt
      sync
    fi

    log_success_msg "Boot partition UUID set to $NEW_BOOT_UUID (was $OLD_BOOT_PARTUUID)"
    log_success_msg "Root partition UUID set to $NEW_ROOT_UUID (was $OLD_ROOT_PARTUUID)"
    log_success_msg "Disk UUID set to $NEW_DISK_UUID"
  else
    OLD_DISKID="$(dd if="$ROOT_DEV" bs=4 count=1 skip=110 status=none | od -An -tx4 | cut -c2-9)"
    dd if=/dev/hwrng "of=$ROOT_DEV" bs=4 seek=110 count=1 conv=notrunc status=none
    DISKID="$(dd if="$ROOT_DEV" bs=4 count=1 skip=110 status=none | od -An -tx4 | cut -c2-9)"

    sed -i "s/$OLD_DISKID/$DISKID/g" "${rootmnt?}/etc/fstab"
    sed -i "s/$OLD_DISKID/$DISKID/" /run/new_diskid/cmdline.txt

    log_success_msg "Disk ID set to $DISKID (was $OLD_DISKID)"
  fi
}

change_btrfs_uuid () {
  if [ "$ROOTFSTYPE" == "btrfs" ]; then
    log_begin_msg "Changing file system UUID..."
    btrfstune -u "$ROOT" <<EOF
y
EOF
    RET=$?
    if [ $RET -ne 0 ]; then
      FAIL_REASON="Change root file system UUID failed\n$FAIL_REASON"
    fi
    return $RET
  fi
}

get_variables

log_begin_msg "Setting new disk ID..."

mkdir -p /run/new_diskid
mount -o remount,rw "$ROOT" "${rootmnt?}/"
mount -o rw "$(resolve_device "$BOOT_PART_DEV")" /run/new_diskid/

if [ "$ROOT_PART_NUM" -eq 2 ]; then
  fix_diskid
else
  log_warning_msg "Disk ID setup skipped due to unexpected partition table"
fi

sed -i 's| resize||g' /run/new_diskid/cmdline.txt
umount /run/new_diskid
umount "$ROOT"

if [ "$ROOT_PART_NUM" -eq 2 ]; then
  change_btrfs_uuid
else
  log_warning_msg "File system ID setup skipped due to unexpected partition table"
fi

mount -o ro "$ROOT" "${rootmnt?}/"
rmdir /run/new_diskid


unset DISKID
unset OLD_DISKID
unset ROOT_PART_NUM
unset ROOT_PART_NAME
unset ROOT_DEV
unset ROOT_DEV_NAME
unset BOOT_PART_DEV
log_end_msg

exit 0
